// Listify/client/app/components/Navbar.jsx
import React from 'react'
import { FaRegPenToSquare } from "react-icons/fa6";

const Navbar = () => {
  return (
    <nav className='h-36 flex justify-between items-center mx-auto my-0 w-6xl px-48'>
           {/* logo */}
           <a className='flex flex-row items-center gap-3 text-3xl' href='/'>
            <span>Listify</span>
            <span><FaRegPenToSquare/></span>
           </a>
            {/* routes */}
            <div className='flex flex-row gap-10 text-xl'>
                <a href={'/auth/'} className='border border-black p-2 px-10 c'>Login</a>
                <a href={'/auth/register'} className='p-2 px-10 justify-center'>Register</a>
            </div>
    </nav>
  )
}

export default Navbar

// prisma-bun-brewcode/src/lib/components/Navbar.svelte
<script>
    import AlignLeft from 'lucide-svelte/icons/align-left';
    import Coffee from 'lucide-svelte/icons/coffee';
	let toggleNav = false;
</script>

<nav class="bg-coffee flex max-w-full items-center justify-between px-20 py-10">
	<a href="/" class="text-6xl font-bold"><Coffee /></a>
	<div class="relative flex flex-col items-end gap-3">
		<button
			class=" w-fit rounded-md border border-white p-1 outline-none transition-all hover:bg-white hover:text-[#6F4E37]"
			on:click={() => (toggleNav = !toggleNav)}><AlignLeft /></button
		>
		<div
			class={`${toggleNav ? 'block' : 'hidden'} absolute top-12 flex flex-col gap-4 border border-white px-4 py-2`}
		>
			<a href="/auth">Login</a>
			<a href="/auth/register">Register</a>
		</div>
	</div>
</nav>
