// prisma-bun-brewcode/src/routes/auth/register/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import errorMessage from '$lib/utils/errorMessage';
	import { hoverUtils } from '$lib/utils/hoverUtils';
	import message from '$lib/utils/message';
	import axios from 'axios';
	import { Eye, EyeOff } from 'lucide-svelte';

	// Static data
	const imageURL =
		'https://static.vecteezy.com/system/resources/previews/026/771/391/large_2x/minimalist-coffee-background-free-photo.jpeg';

	let loading = false;
	let showPassword = false;
	let showConfirmPassword = false;
	// value initialize in show password
	let passwordState = '';
	let confirmPasswordState = '';

	const onRegister = async (e: Event) => {
		e.preventDefault();
		loading = true;

		// get the data
		const userData = new FormData(e.target as HTMLFormElement);
		// initialize the data
		const username = userData.get('username') as string | null;
		const email = userData.get('email') as string | null;
		// form validation
		if (!username || !email || !passwordState || !confirmPasswordState) {
			errorMessage({ message: 'Please input all fields', icon: 'question' });
			loading = false;
			return;
		}

		// validate if the user is writely corrected his/her password
		if (passwordState !== confirmPasswordState) {
			errorMessage({ message: 'Incorrect Password', icon: 'question' });
			loading = false;
			return;
		}

		// post data to the api/auth/register
		try {
			const response = await axios.post('/api/auth/register', userData, {
				headers: { 'Content-Type': 'multipart/form-data' }
			});

			// response status success
			if (response.status === 200) {
				message(response.data.message, 'success');
				setTimeout(() => goto('/dashboard'), 1200);
			}
		} catch (error) {
			// if error occurs to axios post
			if (axios.isAxiosError(error)) {
				errorMessage({ message: error.response?.data.message, icon: 'error' });
			}
			
		} finally {
			loading = false;
		}
	};
</script>

<section class="h-[90vh] overflow-hidden flex justify-center items-center bg-coffee">
	<!-- container -->
	<div class="border border-white w-[800px] h-auto flex flex-row rounded-3xl">
		<img src={imageURL} alt="coffee for login" class="aspect-[9/16] h-auto rounded-l-3xl w-[40%]" />
		<div class="flex justify-center w-[60%] py-10">
			<!-- form -->
			<form class="flex flex-col gap-5 items-center justify-between py-2" on:submit={onRegister}>
				<span class="text-5xl tracking-wider font-bold">REGISTER</span>
				<div class="flex flex-col gap-8">
					<input
						type="text"
						class="bg-transparent border-b-2 border-white focus:border-white focus:outline-none p-2 placeholder:text-gray-300 w-full"
						placeholder="Enter your username"
						name="username"
						autocomplete="off"
					/>
					<input
						type="email"
						class="bg-transparent border-b-2 border-white focus:border-white focus:outline-none p-2 placeholder:text-gray-300 w-full"
						placeholder="Enter your email"
						name="email"
						autocomplete="off"
					/>
					<div class="w-full relative">
						{#if showPassword}
							<input
								type="text"
								autocomplete="off"
								name="password"
								class="bg-transparent border-b-2 border-white focus:border-white focus:outline-none p-2 placeholder:text-gray-300 w-full"
								placeholder="Enter your password"
								bind:value={passwordState}
							/>
							<button
								on:click={() => (showPassword = !showPassword)}
								class="absolute right-2 top-2"
								type="button"><Eye /></button
							>
						{:else}
							<input
								type="password"
								name="password"
								class="bg-transparent border-b-2 border-white focus:border-white focus:outline-none p-2 placeholder:text-gray-300 w-full"
								placeholder="Enter your password"
								bind:value={passwordState}
							/>
							<button
								on:click={() => (showPassword = !showPassword)}
								class="absolute right-2 top-2"
								type="button"><EyeOff /></button
							>
						{/if}
					</div>
					<div class="w-full relative">
						{#if showConfirmPassword}
							<input
								type="text"
								autocomplete="off"
								name="confirmPassword"
								class="bg-transparent border-b-2 border-white focus:border-white focus:outline-none p-2 placeholder:text-gray-300 w-full"
								placeholder="Confirm Password"
								bind:value={confirmPasswordState}
							/>
							<button
								on:click={() => (showConfirmPassword = !showConfirmPassword)}
								class="absolute right-2 top-2"
								type="button"><Eye /></button
							>
						{:else}
							<input
								type="password"
								name="password"
								class="bg-transparent border-b-2 border-white focus:border-white focus:outline-none p-2 placeholder:text-gray-300 w-full"
								placeholder="Confirm Password"
								bind:value={confirmPasswordState}
							/>
							<button
								on:click={() => (showConfirmPassword = !showConfirmPassword)}
								class="absolute right-2 top-2"
								type="button"><EyeOff /></button
							>
						{/if}
					</div>
					<button
						class={`${loading ? 'cursor-not-allowed' : hoverUtils} border p-2`}
						disabled={loading}
					>
						{#if loading}
							<div
								role="status"
								class="inline-block h-5 w-5 mr-2 animate-spin rounded-full border-2 border-solid border-current border-r-transparent align-[-0.125em] motion-reduce:animate-[spin_1.5s_linear_infinite]"
							></div>
						{:else}
							<span>Register</span>
						{/if}
					</button>

					<span>Already Have an Account? <a href="/auth/" class="underline">Login Here</a> </span>
				</div>
			</form>
		</div>
	</div>
</section>

// Listify/client/app/components/Register.jsx
"use client"
import React, { useState } from 'react'
import { MdOutlineMailOutline } from "react-icons/md";
import { FaUserLock } from "react-icons/fa";
import { FaRegUserCircle } from "react-icons/fa";
import handleChange from '../utils/handleChange';
import { useRouter } from 'next/navigation';
import { handleRegister } from '../services/authService';

const Register = () => {
    
    const router = useRouter();
    // states
    const [form, setForm] = useState({
      username: "",
      email: "",
      password: "",
    })
    
    // ui states
    const [loading, setLoading] = useState(false);
    const [showPassword, setShowPassword] = useState(false);

    // function to handle the submit
    const onRegister = async(e) => {

      // prevent from loading the browser
      e.preventDefault();
      setLoading(true);
    
      await handleRegister(form, router, setLoading)
    }
  return (
    <form className='flex flex-col gap-10' onSubmit={onRegister}>
    <h1 className='text-center text-4xl'>Register</h1>
    <div className='flex flex-col gap-5'>
        {/* username */}
      <div className='relative flex items-center'>
            <span className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <FaRegUserCircle className='text-gray-700 text-xl'/>
            </span>
            <input 
             type="text"
             placeholder='Username'
             name='username' 
             className='pl-10 pr-4 border border-black rounded-lg w-full py-3 outline-none text-lg'
             value={form.username}
             onChange={handleChange(setForm)}
             autoComplete='off'
            />
      </div>  {/* email */}
      <div className='relative flex items-center'>
            <span className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <MdOutlineMailOutline className='text-gray-700 text-xl'/>
            </span>
            <input 
             type="email"
             placeholder='Email'
             name='email' 
             className='pl-10 pr-4 border border-black rounded-lg w-full py-3 outline-none text-lg'
             value={form.email}
             onChange={handleChange(setForm)}
             autoComplete='off'
            />
      </div>
      <div className='relative flex items-center'>
            <span className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <FaUserLock className='text-gray-700 text-xl'/>
            </span>
            <input 
             type={showPassword ? "text" : "password"}
             name='password' 
             placeholder='Password' 
             className='pl-10 pr-4 border border-black rounded-lg w-full py-3 outline-none text-lg'
             value={form.password}
             onChange={handleChange(setForm)}
             />
      </div>
      <div className='flex flex-row gap-2'>
        <span>Show Password? </span>
        <input type="checkbox" onClick={() => setShowPassword(!showPassword)}/>
      </div>
     
    </div>
{/* submission */}
<div className='flex flex-col gap-5'>
  <button className={` bg-gray-500 transition-all p-2 text-lg text-white ${loading ? "cursor-not-allowed" : "cursor-pointer"}`} >
         {loading ? (<div
          role="status"
          className="inline-block h-5 w-5 mr-2 animate-spin rounded-full border-2 border-solid border-current border-r-transparent align-[-0.125em] motion-reduce:animate-[spin_1.5s_linear_infinite]">
          </div>) : "Register"}
</button>
  <span>Already have an Account? <a href='/auth/' className='underline'>Login Here</a></span>
</div>
</form>
  )
}

export default Register
