// convox/client/src/lib/components/root/Footer.svelte
<script lang="ts">
	import { preferedDarkUser, dynamicIconSize } from '$lib';
	import { Sun, Moon, MailSearch } from '@lucide/svelte';
</script>

<footer class="flex h-20 w-full items-center justify-between text-2xl">
	<a href="/mail" class="underline max-md:hidden">Collab Here</a>
	<a href="/mail" class="hidden underline max-md:block max-md:no-underline"
		><MailSearch size={$dynamicIconSize} /></a
	>
	<button
		class="cursor-pointer"
		on:click={() => {
			preferedDarkUser.set(!$preferedDarkUser);
		}}
	>
		{#if $preferedDarkUser}
			<Moon size={$dynamicIconSize}/>
		{:else}
			<Sun size={$dynamicIconSize}  />
		{/if}
	</button>
</footer>

// lensshare/client/src/components/root/Footer.vue
<script setup lang="ts">
import { scrollTo, responsivePadding } from "../../utils/rootUtils";
import { Instagram, Facebook, Github, ListStart } from "lucide-vue-next";
</script>

<template>
  <footer
    class="h-[15vh] bg-black text-white px-20 flex justify-between items-center w-screen"
    :class="responsivePadding"
  >
    <a href="/" class="text-2xl font-stardock">LensShare</a>
    <div class="flex flex-row gap-4 items-center max-md:hidden">
      <button class="cursor-pointer" @click="() => scrollTo('home')">
        Home
      </button>
      <button class="cursor-pointer" @click="() => scrollTo('about')">
        About
      </button>
      <button class="cursor-pointer" @click="() => scrollTo('contact')">
        Contact
      </button>
    </div>

    <div class="flex flex-row gap-4 items-center max-md:hidden">
      <a href="https://www.instagram.com/francis_prog/?hl=en"> <Instagram /> </a
      ><a href="https://www.facebook.com/francis.gil.2024"> <Facebook /> </a
      ><a href="https://github.com/Franciss-prog">
        <Github />
      </a>
    </div>

    <button class="hidden max-md:block"><ListStart /></button>
  </footer>
</template>
