// brewcode-next/components/authentication/Navbar.tsx
"use client";
import React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import { AlignRight, CodeXml } from "lucide-react";
const Navbar = () => {
  return (
    <nav className="flex flex-row items-center justify-between px-20 py-10 max-md:px-10">
      {/* logo */}
      <Link href={"/"}>
        <CodeXml />
      </Link>
      {/* Navigations */}
      <section className="flex flex-row gap-20 max-md:hidden"></section>
    </nav>
  );
};

export default Navbar;

// lensshare/client/src/components/root/Navbar.vue
<script setup lang="ts">
import { scrollTo, responsivePadding, showNavbar } from "../../utils/rootUtils";
import { Aperture, ListStart } from "lucide-vue-next";


</script>
<template>
  <header class="absolute w-full">
    <nav
      class="flex justify-between items-center max-w-full px-20 py-5"
      :class="responsivePadding"
    >
      <!-- logo -->
      <a href="/"><Aperture /></a>
      <!-- navs -->
      <div class="flex gap-10 max-md:hidden">
        <button
          class="cursor-pointer hover:underline"
          @click="() => scrollTo('home')"
        >
          Home
        </button>
        <button
          class="cursor-pointer hover:underline"
          @click="() => scrollTo('about')"
        >
          About
        </button>
        <button
          class="cursor-pointer hover:underline"
          @click="() => scrollTo('contact')"
        >
          Contact
        </button>
      </div>
      <!-- routes -->
      <a href="/dashboard" class="max-md:hidden">Rent Now!</a>

      <!-- navbar to toggle for smaller screenss -->
      <button class="hidden max-md:block cursor-pointer" @click="showNavbar"><ListStart /></button>
    </nav>
    
  </header>
</template>
