// prisma-bun-brewcode/src/lib/components/Navbar.svelte
<script>
    import AlignLeft from 'lucide-svelte/icons/align-left';
    import Coffee from 'lucide-svelte/icons/coffee';
	let toggleNav = false;
</script>

<nav class="bg-coffee flex max-w-full items-center justify-between px-20 py-10">
	<a href="/" class="text-6xl font-bold"><Coffee /></a>
	<div class="relative flex flex-col items-end gap-3">
		<button
			class=" w-fit rounded-md border border-white p-1 outline-none transition-all hover:bg-white hover:text-[#6F4E37]"
			on:click={() => (toggleNav = !toggleNav)}><AlignLeft /></button
		>
		<div
			class={`${toggleNav ? 'block' : 'hidden'} absolute top-12 flex flex-col gap-4 border border-white px-4 py-2`}
		>
			<a href="/auth">Login</a>
			<a href="/auth/register">Register</a>
		</div>
	</div>
</nav>

// authify/app/components/Navbar.tsx
"use client";
import React from "react";
import Link from "next/link";
import { ModeToggle } from "./ModeToggle";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { User, UserRound, UsersRound  } from "lucide-react";


const Navbar = () => {
  return (
    <nav className="h-20 flex justify-between items-center px-[200px] py-20">
      {/* logo */}
      <Link className="text-3xl font-extrabold rounded-xl px-3" href={"/"}>
        ATFY
      </Link>
      <div className="flex items-center gap-4 text-xl">
        <ModeToggle />
        <Popover>
          <PopoverTrigger>
            <User />
          </PopoverTrigger>
          <PopoverContent className="flex items-start gap-4 flex-col">
            <div className="text-md flex gap-2 items-center">
              <UserRound/>
              <Link href={"/auth"}>Login</Link>
            </div>
            <div className="text-md flex gap-2 items-center">
                <UsersRound/>
              <Link href={"/auth/register"}>Register</Link>
            </div>
          </PopoverContent>
        </Popover>
      </div>
    </nav>
  );
};

export default Navbar;
